name: xarray_filters_py36
channels:
 - defaults
 - conda-forge # essential for rasterio on osx
dependencies:
 - python=3.6
 - dask
 - numba
 - numpy
 - pandas
 - pytest
 - pytest-cov
 - scikit-learn
 - xarray
 - six
 - attrs
 - conda-forge::rasterio
 - conda-forge::gdal=2.1.*
 - conda-forge::dask-ml
