name: xarray_filters_py35
channels:
 - conda-forge # essential for rasterio on osx
dependencies:
 - python=3.5
 - dask
 - numba
 - numpy
 - pandas
 - pytest
 - pytest-cov
 - scikit-learn
 - xarray
 - six
