name: xarray_filters_py36
channels:
 - defaults
 - conda-forge # essential for rasterio on osx
dependencies:
 - python=3.6
 - dask
 - numba
 - numpy
 - pandas
 - pytest
 - pytest-cov
 - scikit-learn
 - xarray
 - six
 - pip:
    - "--editable=git+https://github.com/dask/dask-glm.git@master#egg=dask-glm_master"
