name: xarray_filters_py27
channels:
 - defaults
 - conda-forge # essential for rasterio on osx
dependencies:
 - python=2.7
 - dask
 - funcsigs
 - numba
 - numpy
 - pandas
 - pytest
 - pytest-cov
 - scikit-learn
 - xarray
 - six
 - pip:
    - "--editable=git+https://github.com/dask/dask-ml.git@master#egg=dask-ml_master"
