name: xarray_filters_py35
channels:
 - defaults
 - conda-forge # essential for rasterio on osx
dependencies:
 - python=3.5
 - dask
 - cython
 - numba
 - numpy
 - pandas
 - pytest
 - pytest-cov
 - scikit-learn
 - xarray
 - six
 - attrs
 - conda-forge::rasterio
 - conda-forge::gdal=2.1.*
 - pip:
    - "--editable=git+https://github.com/dask/dask-ml.git@master#egg=dask-ml_master"
